#' Get legend title for deployment visualizations
#'
#' @param feature Character, one of:
#'   - `n_species`
#'   - `n_events`
#'   - `n_obs`
#'   - `rai_observations`
#'   - `rai_count`
#'   - `effort`
#' @noRd
get_legend_title <- function(feat) {
  # get all legend titles
  titles <- .map_summary_legend_titles
  # return the legend title we need
  titles %>%
    dplyr::filter(.data$feature == feat) %>%
    dplyr::pull(.data$legend_title)
}

#' Add unit to legend title
#'
#' This function is useful when a unit (e.g. temporal unit) should be added to
#' legend title.
#'
#' @param title A character with legend title.
#' @param unit Character with unit to add to `title`.
#' @param use_brackets Logical.
#'   If `TRUE` (default) `unit` is wrapped between brackets, e.g. `(days)`.
#' @noRd
#' @usage add_unit_to_legend_title("My title", unit = "day", use_bracket = TRUE)
add_unit_to_legend_title <- function(title, unit = NULL, use_brackets = TRUE) {
  if (is.null(unit)) {
    title
  } else {
    if (use_brackets == TRUE) {
      unit <- paste0("(", unit, ")")
    }
    paste(title, unit)
  }
}

#' Custom label format function
#'
#' Add "+" to last label of legend while using absolute scale. At the moment
#' only numeric scale is needed and therefore implemented.
#'
#' @source based on leaflet's
#'   [labelFormat()](https://github.com/rstudio/leaflet/commit/bb3ab964486b357ddc160a7032cfdce6cd8fbe35)
#'    function
#'
#' @param max_scale a number indicating the maximum value of the absolute scale
#'   (`NULL` if relative scale is used, default)
#' @param prefix a prefix of legend labels
#' @param suffix a suffix of legend labels
#' @param digits the number of digits of numeric values in labels
#' @param big.mark the thousand separator
#' @param transform a function to transform the label value
#' @noRd
labelFormat_scale <- function(max_scale = NULL,
                              prefix = "",
                              suffix = "",
                              digits = 3,
                              big.mark = ",",
                              transform = identity) {
  formatNum <- function(x, max_scale) {
    cuts_chrs <- format(
      round(transform(x), digits),
      trim = TRUE,
      scientific = FALSE,
      big.mark = big.mark
    )
    if (!is.null(max_scale)) {
      n <- length(x)
      if (x[n] == max_scale) {
        cuts_chrs[n] <- paste0(cuts_chrs[n], "+")
      }
    }
    return(cuts_chrs)
  }
  
  function(type, ...) {
    switch(
      type,
      numeric = (
        function(cuts) {
          paste0(prefix, formatNum(cuts, max_scale), suffix)
        }
      )(...)
    )
  }
}


#' Visualize deployments features
#'
#' This function visualizes deployments features such as number of detected
#' species, number of observations and RAI (Relative Abundance Index) on a
#' dynamic map. The circle size and color are proportional to the mapped
#' feature.
#'
#' @param df Grouped data frame generated by [summarize_deployments()] or
#'   [summarize_observations()] or eventually a subset of it. If columns
#'   `latitude` and `longitude` are not present in `df`, no map can be generated
#'   and an error is returned.
#' @param feature Feature to visualize. One of the columns generated by
#'   [summarize_deployments()] or [summarize_observations()] not used for
#'   grouping. Possible values present in output of [summarize_observations()]
#'   are:
#'   - `n_scientificName`: Number of detected species.
#'   - `n_events`: Number of events observed.
#'   - `n_observations`: Number of observations.
#'   - `sum_count`: Number of individuals observed.
#'   - `rai_observations`: RAI calculated using the number of observations (`n_observations`).
#'   - `rai_count`: RAI calculated using the number of observed individuals (`sum_count`).
#'
#'   Possible values present in output of [summarize_deployments()] are:
#'   - `effort_duration`: Deployment effort duration.
#' @param effort_unit Time unit to use while visualizing deployment effort
#'   duration. Ignored if `feature` is not `"effort_duration"`. One of:
#'   - `second`
#'   - `minute`
#'   - `hour`
#'   - `day`
#'   - `month`
#'   - `year`
#'   If  `NULL` (default), the effort is returned in hours.
#' @param cluster Logical value indicating whether using the cluster option
#'   while visualizing maps. Default: `TRUE`.
#' @param hover_columns Character vector of the columns of `df` to show on mouse
#'   hover. Use `NULL` to disable hovering. Default: all columns in `df` used
#'   for grouping and the `feature` to visualize.
#' @param palette The palette name or the color function that values will be
#'   mapped to. Default: `"inferno"`. Typically one of the following:
#'   - A character vector of RGB or named colors. Examples: `c("#000000",
#'   "#0000FF", "#FFFFFF"))`,`topo.colors(10))`.
#'   - The full name of a RColorBrewer palette, e.g. "BuPu" or "Greens", or
#'   viridis palette: `"viridis"`, `"magma"`, `"inferno"` or `"plasma"`. 
#'   
#'   For more options, see parameter `palette` of [leaflet::colorNumeric()].
#' @param zero_values_show Logical indicating whether to show deployments with
#'   zero values. Default: `TRUE`. See details.
#' @param zero_values_icon_url Character with URL to icon for showing
#'   deployments with zero values.  Use `NULL` if `zero_values_show` is `FALSE`.
#'   Default: a cross (multiply symbol)
#'   `"https://img.icons8.com/ios-glyphs/30/000000/multiply.png"`. See details.
#' @param zero_values_icon_size A number to set the size of the icon to show
#'   groups (e.g. deployments) with zero values. Use `NULL` if
#'   `zero_values_show` is `FALSE`. Default: a cross (multiply symbol)
#'   `"https://img.icons8.com/ios-glyphs/30/000000/multiply.png"`. See details.
#' @param na_values_show Logical indicating whether to show groups (e.g.
#'   deployments) with no observations when feature is `"n_scientificName"`.
#'   Default: `TRUE`. See details.
#' @param na_values_icon_url Character with URL to icon for showing groups (e.g.
#'   deployments) with no observations. Used only if `feature` is
#'   `"n_scientificName"`, ignored otherwise. Use `NULL` if `na_values_show` is
#'   `FALSE`. Default: a red cross (multiply symbol)
#'   `"https://img.icons8.com/ios-glyphs/30/FA5252/multiply.png"`.
#' @param na_values_icon_size A number to set the size of the icon for showing
#'   groups (e.g. deployments) with no observations. Used only if `feature` is
#'   `"n_scientificName"`, ignored otherwise. Use `NULL` if `na_values_show` is
#'   `FALSE`. Default: 10.
#' @param relative_scale Logical indicating whether to use a relative color and
#'   radius scale (`TRUE`) or an absolute scale (`FALSE`). If absolute scale is
#'   used, specify a valid `max_scale`.
#' @param max_scale Number indicating the max value used to map color and
#'   radius.
#' @param radius_range Vector of length 2 containing the lower and upper limit
#'   of the circle radius. The lower value is used for deployments with zero
#'   feature value, e.g. no observations, no identified species, zero RAI or
#'   zero effort. The upper value is used for the deployment(s) with the highest
#'   feature value (`relative_scale` = `TRUE`) or `max_scale` (`relative_scale`
#'   = `FALSE`). Default: `c(10, 50)`.
#'
#' @details Deployments with zero values are shown only if they are present in
#'   the summary, `df`. If you want to show deployments with zero values not
#'   present in the summary, be sure to have used `extend` = `TRUE` in
#'   `summarize_observations()`. See the examples.
#'
#'   Notice also that the argument `species` is not present anymore. If you want
#'   to visualize a feature only for a specific group of species, please filter
#'   the camera trap data package using [filter_observations()] before using
#'   this function. See the examples.
#'
#' @return Leaflet map.
#' @family visualization functions
#' @export
#' @examples
#' \dontrun{
#' x <- example_dataset()
#' # Filter a data package to get only the data of Anas platyrhynchos
#' x_anas_p <- x %>%
#'   filter_observations(scientificName == "Anas platyrhynchos")
#'
#' # Show number of species
#' x %>%
#'   summarize_observations(
#'     group_by = c("deploymentID", "latitude", "longitude")
#'   ) %>%
#'   map_summary("n_scientificName")
#'
#' # Show number of species: show deployments with no
#' # observations (NA icon and size as defaults)
#' x_anas_p %>%
#'   summarize_observations(
#'     group_by = c("deploymentID", "latitude", "longitude"),
#'     extend = TRUE
#'   ) %>%
#'   map_summary("n_scientificName")
#'
#' # Show total number of observations (all species)
#' x %>%
#'   summarize_observations(
#'     group_by = c("deploymentID", "latitude", "longitude")
#'   ) %>%
#'   map_summary("n_observations")
#'
#' # Show number of observations of Anas platyrhynchos  - show deployments with
#' # no observations (zero icon and size  as defaults)
#' x_anas_p %>%
#'   summarize_observations(
#'     group_by = c("deploymentID", "latitude", "longitude"),
#'     extend = TRUE
#'   ) %>%
#'   map_summary("n_observations")
#'
#' # Show number of observations of Anas platyrhynchos without extending the
#' # summary: deployments with no observations are not shown
#' x_anas_p %>%
#'   summarize_observations(
#'     group_by = c("deploymentID", "latitude", "longitude")
#'   ) %>%
#'   map_summary("n_observations")
#'
#' # Same result as above if you extend the summary but use
#' # `zero_values_show` = `FALSE`
#' x_anas_p %>%
#'   summarize_observations(
#'     group_by = c("deploymentID", "latitude", "longitude"),
#'     extend = TRUE
#'   ) %>%
#'   map_summary(
#'     "n_observations",
#'     zero_values_show = FALSE,
#'     zero_values_icon_url = NULL,
#'     zero_values_icon_size = NULL
#'   )
#'
#' # You can eventually filter the species after summarizing,
#' # although it could not be the most efficient way for large Camera Trap Data
#' # Packages
#' library(dplyr)
#' x %>%
#'   summarize_observations(
#'     group_by = c("deploymentID", "latitude", "longitude", "scientificName")
#'   ) %>%
#'   filter(scientificName == "Anas platyrhynchos") %>%
#'   map_summary("n_scientificName")
#'
#' # Show number of individuals
#' x_anas_p %>%
#'   summarize_observations() %>%
#'   map_summary("sum_count")
#'
#' # Show RAI
#' x_anas_p %>%
#'   summarize_observations() %>%
#'   map_summary("rai_observations")
#'
#' # Show RAI (individual counts)
#' x_anas_p %>%
#'   summarize_observations() %>%
#'   map_summary("rai_count")
#'
#' # Show effort (hours)
#' x_anas_p %>%
#'   summarize_deployments() %>%
#'   map_summary("effort_duration")
#'
#' # Show effort (days)
#' x %>%
#'   summarize_deployments() %>%
#'   map_summary("effort_duration", effort_unit = "day")
#'
#' # Show effort per month
#' x %>%
#'   summarize_deployments(group_time_by = "month") %>%
#'   map_summary("effort_duration", effort_unit = "day")
#'
#' # Use viridis palette
#' x_anas_p %>%
#'   summarize_observations() %>%
#'   map_summary("n_observations", palette = "viridis")
#'
#' # Use a palette defined by color names
#' x_anas_p %>%
#'   summarize_observations() %>%
#'   map_summary("n_observations", palette = c("black", "blue", "white"))
#'
#' # Use a palette defined by hex colors
#' x_anas_p %>%
#'   summarize_observations() %>%
#'   map_summary("n_observations", palette = c("#000000", "#0000FF", "#FFFFFF"))
#'
#' # Use same icon but a non default color for zero values deployments,
#' # E.g. red (hex: E74C3C)
#' x_anas_p %>%
#'   summarize_observations(
#'     group_by = c("deploymentID", "latitude", "longitude"),
#'     extend = TRUE
#'   ) %>%
#'   map_summary(
#'     "n_observations",
#'     zero_values_icon_url = "https://img.icons8.com/ios-glyphs/30/E74C3C/multiply.png"
#'   )
#'
#' # Use another icon via a different URL, e.g. the character Fry from Futurama
#' # in green (2ECC71)
#' x_anas_p %>%
#'   summarize_observations(extend = TRUE) %>%
#'   map_summary(
#'     "n_observations",
#'     zero_values_icon_url = "https://img.icons8.com/ios-glyphs/30/2ECC71/futurama-fry.png"
#'   )
#'
#' # Set size of the icon for zero values deployments
#' x %>%
#'   filter_observations(scientificName == "Anas platyrhynchos") %>%
#'   summarize_observations(extend = TRUE) %>%
#'   map_summary("n_observations", zero_values_icon_size = 30)
#'
#' # Use another icon url/size for visualizing groups with no observations
#' (NA, only for `n_scientificName` feature)
#' x %>%
#'   filter_observations(deploymentID != "00a2c20d") %>%
#'   summarize_observations(
#'   group_by = c("deploymentID", "latitude", "longitude")
#'   ) %>%
#'   map_summary(
#'     feature = "n_scientificName",
#'     na_values_icon_url = "https://img.icons8.com/ios-glyphs/30/E74C3C/futurama-fry.png",
#'     na_values_icon_size = 60
#'   )
#'
#' # Disable cluster
#' x %>%
#'   summarize_observations(
#'     group_by = c("deploymentID", "latitude", "longitude")
#'   ) %>%
#'   map_summary("n_observations", cluster = FALSE)
#'
#' # Show only number of observations and location name while hovering
#' x %>%
#'   summarize_observations(
#'     group_by = c("deploymentID", "locationName", "latitude", "longitude")
#'   ) %>%
#'   map_summary(
#'     "n_observations",
#'     hover_columns = c("locationName", "n_observations")
#' )
#'
#' # Use absolute scale for colors and radius
#' x %>%
#'   summarize_observations(
#'     group_by = c("deploymentID", "latitude", "longitude")
#'   ) %>%
#'   map_summary(
#'     "n_scientificName",
#'     relative_scale = FALSE,
#'     max_scale = 4
#' )
#'
#' # Change max and min size circles
#' x %>%
#'   summarize_observations(
#'     group_by = c("deploymentID", "locationName", "latitude", "longitude")
#'   ) %>%
#'   map_summary(
#'     "n_observations",
#'     radius_range = c(40, 150)
#' )
#' }
map_summary <- function(
  df,
  feature,
  effort_unit = NULL,
  cluster = TRUE,
  hover_columns = c(dplyr::group_vars(df), feature),
  palette = "inferno",
  zero_values_show = TRUE,
  zero_values_icon_url = "https://img.icons8.com/ios-glyphs/30/000000/multiply.png",
  zero_values_icon_size = 10,
  na_values_show = TRUE,
  na_values_icon_url = "https://img.icons8.com/ios-glyphs/30/FA5252/multiply.png",
  na_values_icon_size = 10,
  relative_scale = TRUE,
  max_scale = NULL,
  radius_range = c(10, 50)
) {
  # Check `df` is a summary data frame
  check_summary(df)

  # Check columns `latitude` and `longitude` are present in `df`
  assertthat::assert_that(
    all(c("latitude", "longitude") %in% names(df)),
    msg = paste(
      "`df` must contain columns `latitude` and `longitude`.",
      "Ensure these are included in the `group_by` argument when calling",
      "`summarize_observations()` or `summarize_deployments()`."
    )
  )

  # Check columns `latitude` and `longitude` are numeric
  assertthat::assert_that(
    is.numeric(df$latitude),
    is.numeric(df$longitude),
    msg = "Columns `latitude` and `longitude` in `df` must be numeric."
  )

  # Remove rows where latitude and/or longitude are NA and give a warning
  if (any(is.na(df$latitude) | is.na(df$longitude))) {
    n_na_coords <- sum(is.na(df$latitude) | is.na(df$longitude))
    warning(
      glue::glue(
        "{n_na_coords} rows with NA latitude and/or longitude ",
        "removed from `df`."
      )
    )
    df <- df %>%
      dplyr::filter(!is.na(.data$latitude) & !is.na(.data$longitude))
  }

  # Return informative message and empty map if there is no data to plot
  if (nrow(df) == 0) {
    message("No data to show.")
    leaflet_map <-
      leaflet::leaflet() %>%
      leaflet::addTiles() %>%
      leaflet::addControl(htmltools::tags$b(title), position = "bottomright")
    return(leaflet_map)
  }

  # Check that `feature` is a character of length 1
  assertthat::assert_that(
    assertthat::is.string(feature),
    msg = "`feature` must be a character of length 1."
  )

  # Check `feature` is valid, i.e. one of the possible observations/deployments
  # features
  all_features <- c(.features_observations, .features_deployments)
  check_value(
    feature,
    all_features,
    "feature",
    null_allowed = FALSE
  )
  
  # Check `feature` is present in `df`
  assertthat::assert_that(
    feature %in% names(df),
    msg = glue::glue(
      "`feature` '{feature}' not found in `df`. ",
      "Based on your `df`, possible values for `feature` are: ",
      glue::glue_collapse(
        glue::backtick(all_features[all_features %in% names(df)]),
        sep = ", ",
        last = " and "
      )
    )
  )

  # Check `effort_unit` in combination with `feature`
  if (!is.null(effort_unit) & feature != "effort_duration") {
    warning(glue::glue("`effort_unit` ignored for `feature = {feature}`."))
    effort_unit <- NULL
  }

  # Check palette/colors
  viridis_valid_palettes <- c(
    "magma",
    "inferno",
    "plasma",
    "viridis"
  )
  r_color_brewer_palettes <- rownames(RColorBrewer::brewer.pal.info)
  palettes <- c(viridis_valid_palettes, r_color_brewer_palettes)
  if (length(palette) == 1) {
    check_value(
      arg = palette,
      options = palettes,
      arg_name = "palette",
      null_allowed = FALSE
    )
  }

  # Check zero_values_show is a toggle (TRUE or FALSE)
  assertthat::assert_that(
    rlang::is_bool(zero_values_show),
    msg = "zero_values_show must be a logical of length 1: TRUE or FALSE."
  )

  # Check `na_values_show` is a toggle (TRUE or FALSE)
  assertthat::assert_that(
    rlang::is_bool(na_values_show),
    msg = "na_values_show must be a logical of length 1: TRUE or FALSE."
  )

  # Check `zero_values_icon_url` and `zero_values_icon_size` in combination with
  # `zero_values_show`
  if (zero_values_show == FALSE) {
    if (!is.null(zero_values_icon_url)) {
      message(glue::glue(
        "`zero_values_icon_url` is ignored because `zero_values_show` is ",
        "{zero_values_show}."
      ))
      zero_values_icon_url <- NULL
    }
    if (!is.null(zero_values_icon_size)) {
      message(glue::glue(
        "`zero_values_icon_size` is ignored because `zero_values_show` is ",
        "{zero_values_show}."
      ))
      zero_values_icon_size <- NULL
    }
  } else {
    # Check `zero_values_icon_url`
    assertthat::assert_that(
      assertthat::is.string(zero_values_icon_url),
      !is.na(zero_values_icon_url),
      msg = "`zero_values_icon_url` must be a character (URL)."
    )
    # Check `zero_values_icon_size`
    assertthat::assert_that(
      assertthat::is.number(zero_values_icon_size),
      !is.na(zero_values_icon_size),
      msg = "`zero_values_icon_size` must be a number."
    )
  }

  # Check `na_values_icon_url` and `na_values_icon_size` in combination with
  # `na_values_show`
  if (na_values_show == FALSE) {
    if (!is.null(na_values_icon_url)) {
      message(glue::glue(
        "`na_values_icon_url` is ignored because `na_values_show` is ",
        "{na_values_show}."
      ))
      na_values_icon_url <- NULL
    }
    if (!is.null(na_values_icon_size)) {
      message(glue::glue(
        "`na_values_icon_size` is ignored because `na_values_show` is ",
        "{na_values_show}."
      ))
      na_values_icon_size <- NULL
    }
  } else {
    # Check `na_values_icon_url`
    assertthat::assert_that(
      assertthat::is.string(na_values_icon_url),
      !is.na(na_values_icon_url),
      msg = "`na_values_icon_url` must be a character (URL)."
    )
  }

  # Check `cluster`
  assertthat::assert_that(
    rlang::is_bool(cluster),
    msg = "cluster must be a logical: TRUE or FALSE."
  )

  # Check `hover_columns`
  if (!is.null(hover_columns)) {
    # Check `hover_columns` is a character vector
    assertthat::assert_that(
      is.character(hover_columns),
      all(!is.na(hover_columns)),
      msg = "`hover_columns` must be a character vector or `NULL`."
    )
    # Check all values of `hover_columns` are present in `df`
    check_value(
      arg = hover_columns,
      options = names(df),
      arg_name = "hover_columns",
      null_allowed = FALSE
    )
    # Check all `hover_columns` values are allowed
    possible_hover_columns <- .prefixes_for_hover_info$info
    check_value(
      arg = hover_columns,
      options = possible_hover_columns,
      arg_name = "hover_columns",
      null_allowed = TRUE
    )
  }

  # Check combination `relative_scale` and `max_scale`
  if (relative_scale == FALSE) {
    assertthat::assert_that(
      !is.null(max_scale),
      msg = paste(
        "If you use an absolute scale,",
        "`max_scale` must be a number, not `NULL`."
      )
    )
    assertthat::assert_that(
      is.numeric(max_scale),
      msg = paste(
        "If you use an absolute scale,",
        "`max_scale` must be a number."
      )
    )
  }

  if (relative_scale == TRUE & !is.null(max_scale)) {
    warning("Relative scale used: `max_scale` value ignored.")
    max_scale <- NULL
  }

  # Convert effort duration to desired unit if needed
  if (feature == "effort_duration") {
    if (is.null(effort_unit)) {
      effort_unit <- "hour"
    }
    # Convert `effort_duration` to the desired unit
    feat_df <- df %>%
      dplyr::mutate(
        effort_duration = lubridate::time_length(
          .data$effort_duration,
          unit = effort_unit
        )
      )
  } else {
    feat_df <- df
  }

  # Add copy of feature column as `n` for easier handling
  feat_df <- feat_df %>%
    dplyr::mutate(n = .data[[feature]])
  
  # Order the data frame by feature: this will help in plotting the small circles
  # above the big ones
  feat_df <- feat_df %>% dplyr::arrange(.data$n)
  
  # Define title legend
  title <- get_legend_title(feature)
  # Add unit to legend title (for effort)
  title <- add_unit_to_legend_title(
    title,
    unit = effort_unit,
    use_brackets = TRUE
  )

  # Add info while hovering
  if (!is.null(hover_columns)) {
    hover_info_df <- .prefixes_for_hover_info %>%
      dplyr::filter(.data$info %in% hover_columns)
    # Set feature column to n in
    # hover_info_df
    hover_info_df$info[hover_info_df$info == feature] <- "n"
    hover_infos <-
      dplyr::as_tibble(
        purrr::map2(hover_info_df$prefix, hover_info_df$info, function(x, y) {
          info <- feat_df[[y]]
          if (lubridate::is.POSIXt(info)) {
            info <- format(info)
          }
          # Escape HTML to prevent XSS
          escaped_info <- htmltools::htmlEscape(as.character(info))
          paste0(x, escaped_info)
        }),
        .name_repair = "minimal"
      ) %>%
      tidyr::unite(col = "hover_info", sep = "</p><p>")
    hover_infos <-
      hover_infos %>%
      dplyr::mutate(hover_info = paste0("<p>", .data$hover_info, "</p>"))
    hover_infos$hover_info <-
      purrr::map(hover_infos$hover_info, ~ htmltools::HTML(.))
    feat_df <-
      feat_df %>%
      dplyr::bind_cols(hover_infos)
  } else {
    feat_df$hover_info <- NA
  }

  # Set upper limit if absolute value is used and it is lower than some values
  if (relative_scale == FALSE) {
    # Set all n > max_scale to max_scale
    feat_df <-
      feat_df %>%
      dplyr::mutate(
        n = ifelse(.data$n > max_scale, max_scale, .data$n)
      )
  }

  # Max number of species/obs (with possible upper limit  `max_absolute_scale`
  # in case absolute scale is used) to set number of ticks in legend
  max_n <- ifelse(
    is.null(max_scale),
    ifelse(!all(is.na(feat_df$n)), max(feat_df$n, na.rm = TRUE), 0),
    max_scale
  )

  # Define color palette
  pal <- leaflet::colorNumeric(
    palette = palette,
    domain = c(0, max_n)
  )

  # Define bins for ticks of legend
  bins <- 6

  # Define size scale for avoiding too small or too big circles
  radius_max <- radius_range[2]
  radius_min <- radius_range[1]
  if (max_n != 0) {
    conv_factor <- (radius_max - radius_min) / max_n
  } else {
    conv_factor <- 0
  }

  # Define legend values
  legend_values <- seq(from = 0, to = max_n, length.out = bins)

  # Non zero values deploys (n > 0 and is not NA)
  non_zero_values <- feat_df %>% dplyr::filter(.data$n > 0)
  # Zero values
  zero_values <- feat_df %>% dplyr::filter(.data$n == 0)
  # NA values (only returned by n_species)
  na_values <- feat_df %>% dplyr::filter(is.na(.data$n))
  # Make basic start map
  leaflet_map <-
    leaflet::leaflet() %>%
    leaflet::addTiles() %>%
    leaflet::addScaleBar()

  # Add markers for deployments with zero valuesif needed
  if (zero_values_show & nrow(zero_values) > 0) {
    # Create icon for zero values
    zero_icons <- leaflet::icons(
      iconUrl = zero_values_icon_url,
      iconWidth = zero_values_icon_size,
      iconHeight = zero_values_icon_size
    )
    # Add icons for zero values to the map
    leaflet_map <-
      leaflet_map %>%
      leaflet::addMarkers(
        icon = zero_icons,
        data = zero_values,
        lng = ~longitude,
        lat = ~latitude,
        label = ~hover_info,
        clusterOptions = if (cluster == TRUE) {
          leaflet::markerClusterOptions()
        } else {
          NULL
        }
      )
  }

  # Add markers for deployments with NA values if needed
  if (na_values_show & nrow(na_values) > 0) {
    # Create icons for NA values
    na_icons <- leaflet::icons(
      iconUrl = na_values_icon_url,
      iconWidth = na_values_icon_size,
      iconHeight = na_values_icon_size
    )
    # Add icons with NAs to the map
    leaflet_map <-
      leaflet_map %>%
      leaflet::addMarkers(
        icon = na_icons,
        data = na_values,
        lng = ~longitude,
        lat = ~latitude,
        label = ~hover_info,
        clusterOptions = if (cluster == TRUE) {
          leaflet::markerClusterOptions()
        } else {
          NULL
        }
      )
  }
  if (nrow(non_zero_values) > 0) {
    leaflet_map <-
      leaflet_map %>%
      leaflet::addCircleMarkers(
        data = non_zero_values,
        lng = ~longitude,
        lat = ~latitude,
        radius = ~ ifelse(is.na(n), radius_min, n * conv_factor + radius_min),
        color = ~ pal(n),
        stroke = FALSE,
        fillOpacity = 0.8,
        label = ~hover_info,
        clusterOptions = if (cluster == TRUE) {
          leaflet::markerClusterOptions()
        } else {
          NULL
        }
      ) %>%
      leaflet::addLegend(
        "bottomright",
        pal = pal,
        values = legend_values,
        title = title,
        opacity = 1,
        bins = bins,
        na.label = "",
        labFormat = labelFormat_scale(max_scale = max_scale)
      )
  }
  leaflet_map
}
