#' Import Wildlife Insight camera trap data to Camera Trap Data Package
#'
#' Transforms a [Wildlife Insight (WI)](https://www.wildlifeinsights.org/)
#' dataset to [Camera Trap Data Package](https://tdwg.github.io/camtrap-dp/)
#' data exchange format.
#'
#' Wildlife Insight offers to export your dataset [as private download](
#' https://www.wildlifeinsights.org/get-started/download/private) or
#' [public download](
#' https://www.wildlifeinsights.org/get-started/data-download/public).
#' This function read the zip file from the download and convert the Projects,
#' Cameras, Deployments csv file to Darwin Core standard
#'
#' @param directory Path to local directory to read the WI files
#' @param rightsHolder Acronym of the organization owning or managing the
#' rights over the data.
#' @param coordinateUncertaintyInMeters Uncertainty of the coordinate in meters.
#' @param captureMethod Either `"motion detection"` or `"time lapse"`.
#' @return CSV (data) files written to disk.
#' @export
read_wi <- function(directory = ".",
                    rightsHolder = "project_admin_organization",
                    coordinateUncertaintyInMeters = 30,
                    captureMethod = "motion detection") {

  assertthat::assert_that(dir.exists(directory))
  assertthat::assert_that(assertthat::is.string(rightsHolder))
  assertthat::assert_that(assertthat::is.number(coordinateUncertaintyInMeters))
  assertthat::assert_that(captureMethod=="motion detection" | captureMethod=="time lapse")
  
  # Get file location and check existence
  deployments_file <- file.path(directory, "deployments.csv")
  if (!file.exists(deployments_file)) {
    stop(paste0("The deployments file does not exist: ", deployments_file))
  }
  images_file <- file.path(directory, "images.csv")
  if (!file.exists(images_file)) {
    stop(paste0("The images file does not exist: ", images_file))
  }
  cameras_file <- file.path(directory, "cameras.csv")
  if (!file.exists(cameras_file)) {
    stop(paste0("The cameras file does not exist: ", cameras_file))
  }
  projects_file <- file.path(directory, "projects.csv")
  if (!file.exists(cameras_file)) {
    stop(paste0("The project file does not exist: ", projects_file))
  }

  # Read data from file
  wi_deployments <- readr::read_csv(deployments_file, show_col_types = FALSE)
  wi_images <- readr::read_csv(images_file, show_col_types = FALSE)
  wi_cameras <- readr::read_csv(cameras_file, show_col_types = FALSE)
  wi_projects <- readr::read_csv(projects_file, show_col_types = FALSE)

  # Check that there is only a single project
  assertthat::assert_that(nrow(wi_projects) == 1)
  wi_project <- as.list(wi_projects[1:1, ])
  wi_project$ark_id <- stringr::str_extract(
    wi_project$data_citation,
    "http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+"
  )

  # Create the package
  package <- frictionless::create_package()

  # Package Properties (see https://tdwg.github.io/camtrap-dp/metadata)
  package$name <- basename(directory) # package name is extracted as the zip folder unique to the WI export (e.g. wildlife-insights_6d7bf890-fcf5-4e3f-9942-67cb17480df8_project-2001317_data)
  package$id <- wi_project$ark_id # (e.g. http://n2t.net/ark:/63614/w12001317)
  # package$profile # generated by frictionless::create_package()
  package$created <- strftime(as.POSIXlt(Sys.time(), "UTC"), "%Y-%m-%dT%H:%M:%S%z")
  package$licenses <- list(
    list(
      name = wi_project$metadata_license,
      scope = "data"
    ),
    list(
      name = unique(wi_images$license),
      scope = "media"
    )
  )
  package$sources <- c(list(
    title = "Wildlife Insight",
    path = "https://www.wildlifeinsights.org/"
  ))
  package$contributors <- list(list(
    title = wi_project$project_admin,
    email = wi_project$project_admin_email
  ))
  # package$resources =  # generated by frictionless::create_package()
  package$organizations <- list(list(title = wi_project$project_admin_organization))
  package$rightsHolder <- ifelse(rightsHolder == "project_admin_organization",
    wi_project$project_admin_organization, rightsHolder
  )
  package$bibliographicCitation <- stringr::str_replace_all(wi_project$data_citation, "[\r\n]", "")
  package$project <- list(
    id = toString(wi_project$project_id),
    title = wi_project$project_name,
    acronym = wi_project$project_short_name,
    description = wi_project$project_objectives,
    path = wi_project$ark_id,
    samplingDesign = dplyr::case_when(
      wi_project$project_sensor_layout == "Systematic" ~ "systematic random",
      wi_project$project_sensor_layout == "Randomized" ~ "simple random",
      wi_project$project_sensor_layout == "Convinience" ~ "opportunistic",
      wi_project$project_sensor_layout == "Targeted" ~ "targeted",
    ),
    captureMethod = captureMethod,
    animalTypes = ifelse(mean(is.na(wi_images$markings)) == 1, "unmarked", ifelse(mean(is.na(wi_images$markings)) == 0, "marked", c("marked", "unmarked"))), # marked and/or unmarked
    classificationLevel = ifelse(wi_project$project_type == "Image", "media", "sequence") # Need to check how WI export sequence data.
    # sequenceInterval # deployment specific, see https://github.com/tdwg/camtrap-dp/issues/203
    # references # none used in WI
  )
  package$spatial <- list(
    type = "Feature",
    bbox = list(
      min(wi_deployments$longitude),
      min(wi_deployments$latitude),
      max(wi_deployments$longitude),
      max(wi_deployments$latitude)
    ),
    properties = stats::setNames(list(), character(0)),
    geometry = list(
      type = "Polygon",
      coordinates = list(list(
        list(min(wi_deployments$longitude), min(wi_deployments$latitude)),
        list(max(wi_deployments$longitude), min(wi_deployments$latitude)),
        list(max(wi_deployments$longitude), max(wi_deployments$latitude)),
        list(min(wi_deployments$longitude), max(wi_deployments$latitude)),
        list(min(wi_deployments$longitude), min(wi_deployments$latitude))
      ))
    )
  )
  package$temporal <- list(
    start = min(wi_deployments$start_date),
    end = max(wi_deployments$end_date)
  )
  package$taxonomic <- wi_images %>%
    dplyr::transmute(
      taxonID = .data$wi_taxon_id,
      taxonIDReference = "https://github.com/ConservationInternational/Wildlife-Insights----Data-Migration/tree/master/WI_Global_Taxonomy",
      scientificName = ifelse(.data$species != "", paste0(.data$genus, " ", .data$species),
        ifelse(.data$genus != "", .data$genus,
          ifelse(.data$family != "", .data$family,
            ifelse(.data$order != "", .data$order, .data$class)
          )
        )
      ),
      taxonRank = ifelse(.data$species != "", "species",
        ifelse(.data$genus != "", "genus",
          ifelse(.data$family != "", "family",
            ifelse(.data$order != "", "order", "class")
          )
        )
      )
      # kingdom = "Animalia",
      # phylum = , # not present
      # class,
      # order,
      # family,
      # subfamily = , # not present
      # genus 
    ) %>%
    unique() %>%
    purrr::transpose()
  package$platform <- list(
    title = "Wildlife Insight",
    path = "https://www.wildlifeinsights.org/"
    # version = "",
    # packageID = ""
  )

  # deployments (see https://tdwg.github.io/camtrap-dp/data/#deployments)
  deployments <- wi_deployments %>%
    dplyr::left_join(wi_cameras, by = c("project_id", "camera_id")) %>%
    dplyr::transmute(
      deploymentID = .data$deployment_id,
      # locationID = .data$placename,
      locationName = .data$placename,
      longitude = .data$longitude,
      latitude = .data$latitude,
      coordinateUncertainty = coordinateUncertaintyInMeters,
      start = .data$start_date,
      end = .data$end_date,
      setupBy = .data$recorded_by,
      cameraID = as.character(.data$camera_id),
      cameraModel = .data$model,
      cameraInterval = .data$quiet_period,
      cameraHeight = dplyr::case_when(
        .data$sensor_height == "Chest height" ~ 100,
        .data$sensor_height == "Knee height" ~ 50,
        .data$sensor_height == "Canopy" ~ 3, # huge range depending on your forest...
        .data$sensor_height == "Unknown" ~ NA_real_, # not sure how to make this facultative?
        .data$sensor_height == "Other" ~ NA_real_, # .data$height_other is a description
      ),
      cameraTilt = NA_integer_,
      cameraHeading = .data$sensor_orientation,
      detectionDistance = NA_real_,
      timestampIssues = FALSE,
      baitUse = tolower(.data$bait_type),
      session = NA_character_, # subproject_name?
      array = NA_character_,
      featureType = tolower(.data$feature_type),
      habitat = NA_character_,
      tags = NA_character_,
      comments = NA_character_, # event_description?
      `_id` = NA_character_
    )

  # https://tdwg.github.io/camtrap-dp/data/#media
  media <- wi_images %>%
    dplyr::transmute(
      mediaID = .data$image_id,
      deploymentID = .data$deployment_id,
      sequenceID = NA_character_,
      captureMethod = captureMethod,
      timestamp = .data$timestamp,
      filePath = .data$location,
      fileName = .data$filename,
      fileMediatype = paste0("image/", tolower(tools::file_ext(.data$location))),
      exifData = NA_character_,
      favourite = .data$highlighted,
      comments = NA_character_,
      `_id` = NA_character_
    ) %>%
    unique() # unique remove the images with multiple observations

  # https://tdwg.github.io/camtrap-dp/data/#observations
  observations <- wi_images %>%
    dplyr::transmute(
      observationID = paste(.data$image_id, .data$wi_taxon_id),
      deploymentID = .data$deployment_id,
      sequenceID = NA_character_,
      mediaID = .data$image_id,
      timestamp = .data$timestamp,
      observationType = dplyr::case_when(
        species == "sapiens" ~ "human",
        # common_name == "common_name" ~ "unknown",
        is_blank == 1 ~ "blank",
        class %in% c(
          "Mammalia", "Aves", "Reptilia", "Amphibia", "Arachnida", "Gastropoda",
          "Malacostraca", "Clitellata", "Chilopoda", "Diplopoda", "Insecta"
        ) ~ "animal",
        class %in% c("CV Needed", "CV Failed", "No CV Result") ~ "unclassified",
        TRUE ~ "unknown"
      ),
      cameraSetup = NA,
      taxonID = .data$wi_taxon_id,
      scientificName = paste0(.data$genus, " ", .data$species),
      count = .data$number_of_objects,
      countNew = NA_integer_,
      lifeStage = tolower(.data$age),
      sex = tolower(.data$sex),
      behaviour = NA_character_,
      individualID = NA_character_, # individual_id or animal_recognizable? I am not sure what are WI export option if that is the case?
      classificationMethod = ifelse(is.na(.data$cv_confidence), "human", "machine"),
      classifiedBy = .data$identified_by,
      classificationTimestamp = NA,
      classificationConfidence = .data$cv_confidence, # or uncertainty ? not sure of the difference
      comments = .data$individual_animal_notes,
      `_id` = NA_character_
      # Not use: license and markings.
    )


  # Add data frames as resources (in separate steps for better error handling)
  # TODO: enable as part of https://github.com/inbo/camtraptor/issues/144
  # package <- frictionless::add_resource(
  #   package,
  #   resource_name = "deployments",
  #   data = deployments,
  #   schema = "https://raw.githubusercontent.com/tdwg/camtrap-dp/0.1.7/deployments-table-schema.json"
  # )
  # package <- frictionless::add_resource(
  #   package,
  #   resource_name = "media",
  #   data = media,
  #   schema = "https://raw.githubusercontent.com/tdwg/camtrap-dp/0.1.7/media-table-schema.json"
  # )
  # package <- frictionless::add_resource(
  #   package,
  #   resource_name = "observations",
  #   data = observations,
  #   schema = "https://raw.githubusercontent.com/tdwg/camtrap-dp/0.1.7/observations-table-schema.json"
  # )

  # Check
  package$data <- list(
    deployments = deployments,
    media = media,
    observations = observations
  )

  return(package)
}
