#' Import Wildlife Insight camera trap data to Camera Trap Data Package
#'
#' Transforms a [Wildlife Insight (WI)](https://www.wildlifeinsights.org/)
#' dataset to [Camera Trap Data Package](https://tdwg.github.io/camtrap-dp/)
#' data exchange format.
#'
#' Wildlife Insight offers to export your dataset [as private download](
#' https://www.wildlifeinsights.org/get-started/download/private) or
#' [public download](
#' https://www.wildlifeinsights.org/get-started/data-download/public).
#' This function read the zip file from the download and convert the Projects,
#' Cameras, Deployments csv file to Darwin Core standard
#'
#' @param directory Path to local directory to read the WI files
#' @param rights_holder Acronym of the organization owning or managing the
#' rights over the data.
#' @param coordinateUncertaintyInMeters Uncertainty of the coordinate in meters.
#' @param captureMethod Either `"motion detection"` or `"time lapse"`.
#' @return CSV (data) files written to disk.
#' @export
read_wi <- function(directory = ".",
                    rightsHolder = "project_admin_organization",
                    coordinateUncertaintyInMeters = 30,
                    captureMethod = "motion detection") {
  if (!file.exists(directory)) {
    stop(paste0("The import directory does not exist: ", directory))
  }

  # If zip file, unzip
  if (tools::file_ext(directory) == "zip") {
    utils::unzip(directory, exdir = dirname(directory))
    directory <- tools::file_path_sans_ext(directory)
  }

  # Get file location and check existence
  deployments_file <- file.path(directory, "deployments.csv")
  if (!file.exists(deployments_file)) {
    stop(paste0("The deployments file does not exist: ", deployments_file))
  }
  images_file <- file.path(directory, "images.csv")
  if (!file.exists(images_file)) {
    stop(paste0("The images file does not exist: ", images_file))
  }
  cameras_file <- file.path(directory, "cameras.csv")
  if (!file.exists(cameras_file)) {
    stop(paste0("The cameras file does not exist: ", cameras_file))
  }
  projects_file <- file.path(directory, "projects.csv")
  if (!file.exists(cameras_file)) {
    stop(paste0("The project file does not exist: ", projects_file))
  }

  # Read data from file
  wi_deployments <- readr::read_csv(deployments_file, show_col_types = FALSE)
  wi_images <- readr::read_csv(images_file, show_col_types = FALSE)
  wi_cameras <- readr::read_csv(cameras_file, show_col_types = FALSE)
  wi_projects <- readr::read_csv(projects_file, show_col_types = FALSE)

  # Check that there is only a single project
  assertthat::assert_that(nrow(wi_projects) == 1)

  wi_projects <- wi_projects %>% dplyr::mutate(
    samplingDesign = dplyr::case_when(
      .data$project_sensor_layout == "Systematic" ~ "systematic random",
      .data$project_sensor_layout == "Randomized" ~ "simple random",
      .data$project_sensor_layout == "Convinience" ~ "opportunistic",
      .data$project_sensor_layout == "Targeted" ~ "targeted",
    ),
    ark_id = stringr::str_extract(
      .data$data_citation,
      "http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+"
    )
  )

  wi_images <- wi_images %>% dplyr::mutate(
    observationType = dplyr::case_when(
      species == "sapiens" ~ "human",
      # common_name == "common_name" ~ "unknown",
      is_blank == 1 ~ "blank",
      class %in% c(
        "Mammalia", "Aves", "Reptilia", "Amphibia", "Arachnida", "Gastropoda",
        "Malacostraca", "Clitellata", "Chilopoda", "Diplopoda", "Insecta"
      ) ~ "animal",
      class %in% c("CV Needed", "CV Failed", "No CV Result") ~ "unclassified",
      TRUE ~ "unknown"
    )
  )


  # Create the package
  package <- frictionless::create_package()

  # Package Properties (see https://tdwg.github.io/camtrap-dp/metadata)
  package$name <- basename(directory) # package name is extracted as the zip folder unique to the WI export (e.g. wildlife-insights_6d7bf890-fcf5-4e3f-9942-67cb17480df8_project-2001317_data)
  package$id <- wi_projects$ark_id # (e.g. http://n2t.net/ark:/63614/w12001317)
  # package$profile # generated by frictionless::create_package()
  package$created <- Sys.Date()
  package$licenses <- wi_projects$metadata_license
  package$sources <- c(list(
    title = "Wildlife Insight",
    path = "https://www.wildlifeinsights.org/"
  ))
  package$contributors <- list(list( # check with writejson
    title = wi_projects$project_admin,
    email = wi_projects$project_admin_email
  ))
  # package$resources =  # generated by frictionless::create_package()
  package$organizations <- list(title = wi_projects$project_admin_organization)
  package$rightsHolder <- ifelse(rightsHolder == "project_admin_organization",
    wi_projects$project_admin_organization, rightsHolder
  )
  package$bibliographicCitation <- wi_projects$data_citation
  package$project <- list(
    id = wi_projects$project_id,
    title = wi_projects$project_name,
    acronym = wi_projects$project_short_name,
    description = wi_projects$project_objectives,
    path = wi_projects$ark_id,
    samplingDesign = wi_projects$samplingDesign, # see above how this this computed
    captureMethod = captureMethod,
    animalTypes = ifelse(mean(is.na(wi_images$markings)) == 1, "unmarked", ifelse(mean(is.na(wi_images$markings)) == 0, "marked", c("marked", "unmarked"))), # marked and/or unmarked
    classificationLevel = ifelse(wi_projects$project_type == "Image", "media", "sequence") # Need to check how WI export sequence data.
    # sequenceInterval # deployment specific, see https://github.com/tdwg/camtrap-dp/issues/203
    # references # none used in WI
  )
  package$spatial <- list(
    type = "Feature",
    bbox = list(
      min(wi_deployments$longitude),
      min(wi_deployments$latitude),
      max(wi_deployments$longitude),
      max(wi_deployments$latitude)
    ),
    properties = list(),
    geometry = list(
      type = "Polygon",
      coordinates = list(
        list(min(wi_deployments$longitude), min(wi_deployments$latitude)),
        list(max(wi_deployments$longitude), min(wi_deployments$latitude)),
        list(max(wi_deployments$longitude), max(wi_deployments$latitude)),
        list(min(wi_deployments$longitude), min(wi_deployments$latitude)),
        list(min(wi_deployments$longitude), min(wi_deployments$latitude))
      )
    )
  )
  package$temporal <- list(
    start = min(wi_deployments$start_date),
    end = max(wi_deployments$end_date)
  )
  package$taxonomic <- wi_images %>%
    dplyr::transmute(
      taxonID = .data$wi_taxon_id,
      taxonIDReference = "https://github.com/ConservationInternational/Wildlife-Insights----Data-Migration/tree/master/WI_Global_Taxonomy",
      taxonRank = ifelse(.data$species != "", "species",
        ifelse(.data$genus != "", "genus",
          ifelse(.data$family != "", "family",
            ifelse(.data$order != "", "order", "class")
          )
        )
      ),
      scientificName = ifelse(.data$species != "", paste0(.data$genus, " ", .data$species),
        ifelse(.data$genus != "", .data$genus,
          ifelse(.data$family != "", .data$family,
            ifelse(.data$order != "", .data$order, .data$class)
          )
        )
      )
    ) %>%
    unique() %>%
    purrr::transpose()
  package$platform <- list(
    title = "Wildlife Insight",
    path = "https://www.wildlifeinsights.org/"
    # version = "",
    # packageID = ""
  )

  # deployments (see https://tdwg.github.io/camtrap-dp/data/#deployments)
  deployments <- wi_deployments %>%
    dplyr::left_join(wi_cameras, by = c("project_id", "camera_id")) %>%
    dplyr::transmute(
      deploymentID = .data$deployment_id,
      locationName = .data$placename,
      locationID = .data$placename,
      .data$longitude,
      .data$latitude,
      coordinateUncertainty = coordinateUncertaintyInMeters,
      start = .data$start_date,
      end = .data$end_date,
      setupBy = .data$recorded_by,
      cameraID = .data$camera_id,
      cameraModel = .data$model,
      cameraInterval = .data$quiet_period,
      cameraHeight = .data$sensor_height,
      # cameraTilt = NULL,
      cameraHeading = .data$sensor_orientation,
      # detectionDistance = NULL,
      # timestampIssues = FALSE,
      baitUse = tolower(.data$bait_type),
      # session subproject_name?
      # array ?
      featureType = tolower(.data$feature_type),
      # habitat
      # tags
      # comments = event_description?
      # _id
    )

  # https://tdwg.github.io/camtrap-dp/data/#media
  media <- wi_images %>%
    dplyr::transmute(
      mediaID = .data$image_id,
      deploymentID = .data$deployment_id,
      # sequenceID
      captureMethod = captureMethod,
      timestamp = .data$timestamp,
      filePath = .data$location,
      fileName = .data$filename,
      fileMediatype = "image/jpeg", # tools::file_ext(.data$location) would return ".jpg), should we use this?
      # exifData
      favorite = .data$highlighted,
      # comments =
      # _id
    ) %>%
    unique() # unique remove the images with multiple observations

  # https://tdwg.github.io/camtrap-dp/data/#observations
  observations <- wi_images %>%
    dplyr::transmute(
      observationID = paste(.data$image_id, .data$wi_taxon_id),
      deploymentID = .data$deployment_id,
      # sequenceID
      mediaID = .data$image_id,
      timestamp = .data$timestamp, # why do we need this again? How can it be different from media$timestamp
      observationType = .data$observationType,
      # cameraSetup
      taxonID = .data$wi_taxon_id, # Why this is not required?
      # scientificName = paste0(.data$genus, " ", .data$species), Why do we need this again here?
      count = .data$number_of_objects,
      # countNew
      lifeStage = tolower(.data$age),
      sex = tolower(.data$sex),
      # behaviour
      # individualID = individual_id or animal_recognizable ?  I am not sure what are WI export option if that is the case?
      classificationMethod = ifelse(is.na(.data$cv_confidence), "human", "machine"),
      classifiedBy = .data$identified_by,
      # classificationTimestamp
      classificationConfidence = .data$cv_confidence, # or uncertainty ? not sure of the difference
      comments = .data$individual_animal_notes,
      # _id
      # Not use: license and markings.
    )


  # To be use in the future
  # package <- package %>%
  #   frictionless::add_resource(
  #     package,
  #     resource_name = "deployments",
  #     data = deployments,
  #     schema = "https://raw.githubusercontent.com/tdwg/camtrap-dp/0.1.7/deployments-table-schema.json"
  #   ) %>%
  #   frictionless::add_resource(
  #     package,
  #     resource_name = "media",
  #     data = media,
  #     schema = "https://raw.githubusercontent.com/tdwg/camtrap-dp/0.1.7/media-table-schema.json"
  #   ) %>%
  #   frictionless::add_resource(
  #     package,
  #     resource_name = "observations",
  #     data = observations,
  #     schema = "https://raw.githubusercontent.com/tdwg/camtrap-dp/0.1.7/observations-table-schema.json"
  #   )


  # Check
  package$data <- list(
    deployments = deployments,
    media = media,
    observations = observations
  )

  return(package)
}
