name: pkgcheck

# This will cancel running jobs once a new run is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  workflow_run: # The lines below should be added to prevent the pkgcheck 
                # action to fail if it completes while other workflows are still running
    workflows: ["R-CMD-check.yaml", "test-coverage.yaml"]
    types: [completed]
    branches: [main, master]
  # Manually trigger the Action under Actions/pkgcheck
  workflow_dispatch:
  # Run on every push to main
  push:
    branches:
      - main
      - pkgcheck-action

jobs:
  pkgcheck:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: ropensci-review-tools/pkgcheck-action@main
